INSERT INTO organization.hospitals (
    id,
    name,
    hospital_code,
    registration_number,
    email,
    phone,
    website,
    logo_url,
    address,
    city,
    state,
    country,
    postal_code,
    timezone,
    currency,
    status,
    created_at,
    updated_at
)
VALUES (
           '11111111-1111-1111-1111-111111111111',
           'CityCare Multispeciality Hospital',
           'CCH001',
           'AP-HOSP-2026-001',
           'info@citycarehospital.com',
           '+91-40-4567-8901',
           'https://www.citycarehospital.com',
           NULL,
           'Road No. 12, Banjara Hills',
           'Hyderabad',
           'Telangana',
           'India',
           '500034',
           'Asia/Kolkata',
           'INR',
           'ACTIVE',
           CURRENT_TIMESTAMP,
           CURRENT_TIMESTAMP
       );